# Generated by Django 5.2.9 on 2026-05-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.trader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                ("receipt_number", models.CharField(max_length=100, unique=True)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PAID", max_length=20)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.trader",
                    ),
                ),
            ],
        ),
    ]
