# Generated by Django 5.2.9 on 2026-05-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_debt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tax",
        ),
    ]
