# Generated by Django 5.2.9 on 2026-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("national_id", models.CharField(max_length=30)),
                ("pin", models.CharField(max_length=10)),
            ],
        ),
    ]
