# Generated by Django 5.2.9 on 2026-05-14 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="amount",
            new_name="loan_amount",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="created_at",
        ),
        migrations.AddField(
            model_name="loan",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="application_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="loan",
            name="approved_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="loan",
            name="duration_months",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name="loan",
            name="remaining_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
