# Generated by Django 5.2.9 on 2026-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loanpayment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoanPayment",
            new_name="LoanRepayment",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="purpose",
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration_months",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="loan",
            name="remaining_balance",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
