# Generated by Django 5.2.9 on 2026-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_rename_loanpayment_loanrepayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="penalty_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
