# Generated by Django 5.2.9 on 2026-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loan_penalty_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration_months",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
