# Generated by Django 5.2.9 on 2026-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_alter_loan_due_date_alter_loan_duration_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
