# Generated by Django 5.2.9 on 2026-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_loan_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="credit_score",
            field=models.IntegerField(default=0),
        ),
    ]
