# Generated by Django 5.2.9 on 2026-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="MicrofinanceOfficer",
        ),
    ]
